services:
  network_event_manager:
    image: ${SEQAM_NETWORK_EVENT_MANAGER_IMAGE_NAME}
    container_name: seqam-network-event-manager-bare
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 7500M
    ports:
      - "9002:8887"
      - "5201:5201"
    environment:
      - OTLP_URL=${OTLP_URL}
